import { Tag, Album, Photo } from '@/app/types';

export const mockTags: Tag[] = [
    { id: 'projects', name: 'Projects', color: '#34D399' }, // green
    { id: 'instaff', name: 'InStaff.jobs', color: '#F59E0B' }, // orange
    { id: 'personal', name: 'Personal', color: '#3B82F6' }, // blue
    { id: 'travel', name: 'Travel', color: '#8B5CF6' }, // purple
    { id: 'food', name: 'Food & Drinks', color: '#EC4899' }, // pink
    { id: 'work', name: 'Work', color: '#6B7280' }, // gray
    { id: 'urban', name: 'Urban', color: '#EF4444' }, // red
    { id: 'landscape', name: 'Landscape', color: '#0EA5E9' }, // sky blue
];

export const mockAlbums: Album[] = [
    { id: 'all', name: 'All Photos' },
    { id: 'nature', name: 'Nature' },
    { id: 'architecture', name: 'Architecture' },
    { id: 'portraits', name: 'Portraits' },
    { id: 'street', name: 'Street' },
    { id: 'favorites', name: 'Favorites' },
    { id: 'travel', name: 'Travel' },
    { id: 'food', name: 'Food & Cuisine' },
];

export const mockPhotos: Photo[] = [
    {
        id: 1,
        album: 'nature',
        url: 'https://images.unsplash.com/photo-1472214103451-9374bd1c798e?w=1200&h=800&fit=crop',
        title: 'Mountain View',
        description: 'Beautiful mountain landscape with a clear blue sky',
        date: '2024-03-15',
        orientation: 'landscape',
        tags: ['projects', 'travel'],
    },
    {
        id: 2,
        album: 'architecture',
        url: 'https://images.unsplash.com/photo-1511818966892-d7d671e672a2?w=1200&h=1600&fit=crop',
        title: 'Modern Building',
        description: 'Contemporary architecture with clean lines and glass facades',
        date: '2024-03-14',
        orientation: 'portrait',
        tags: ['instaff', 'urban'],
    },
    {
        id: 3,
        album: 'portraits',
        url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=1200&h=1600&fit=crop',
        title: 'Portrait Study',
        description: 'Professional portrait with natural lighting',
        date: '2024-03-13',
        orientation: 'portrait',
        tags: ['personal', 'work'],
    },
    {
        id: 4,
        album: 'street',
        url: 'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?w=1200&h=800&fit=crop',
        title: 'City Life',
        description: 'Busy street scene capturing the energy of urban life',
        date: '2024-03-12',
        orientation: 'landscape',
        tags: ['urban'],
    },
    {
        id: 5,
        album: 'nature',
        url: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=2400&h=800&fit=crop',
        title: 'Forest Path',
        description: 'Serene forest trail with sunlight filtering through the trees',
        date: '2024-03-11',
        orientation: 'wide',
        tags: ['projects', 'personal'],
    },
    {
        id: 101,
        album: 'landscape',
        url: 'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?w=1200&h=800&fit=crop',
        title: 'Mountain Reflection',
        description: 'Serene mountain lake with perfect reflections in early morning light',
        date: '2023-11-15',
        orientation: 'landscape',
        tags: ['landscape', 'travel'],
    },
    {
        id: 103,
        album: 'architecture',
        url: 'https://images.unsplash.com/photo-1519160558534-579f5106e43f?w=1200&h=1600&fit=crop',
        title: 'Modern Skyscraper',
        description: 'Impressive modern skyscraper with glass facade reaching into blue sky',
        date: '2023-09-18',
        orientation: 'portrait',
        tags: ['urban'],
    },
    {
        id: 105,
        album: 'food',
        url: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=1200&h=1600&fit=crop',
        title: 'Pizza Perfection',
        description: 'Homemade Italian pizza with fresh ingredients straight from the oven',
        date: '2023-07-14',
        orientation: 'portrait',
        tags: ['food', 'personal'],
    },
    {
        id: 106,
        album: 'portraits',
        url: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=1200&h=1600&fit=crop',
        title: 'Thoughtful Moment',
        description: 'Young man looking contemplatively into the distance',
        date: '2023-06-19',
        orientation: 'portrait',
        tags: ['personal'],
    },
    {
        id: 107,
        album: 'night',
        url: 'https://images.unsplash.com/photo-1507400492013-162706c8c05e?w=1200&h=800&fit=crop',
        title: 'City Nightscape',
        description: 'Dazzling city lights illuminating the urban landscape after sunset',
        date: '2023-05-03',
        orientation: 'landscape',
        tags: ['urban'],
    },
    {
        id: 108,
        album: 'nature',
        url: 'https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=1200&h=800&fit=crop',
        title: 'Sunlit Forest',
        description: 'Sunlight streaming through dense forest canopy creating magical atmosphere',
        date: '2023-04-22',
        orientation: 'landscape',
        tags: ['landscape'],
    },
    {
        id: 109,
        album: 'travel',
        url: 'https://images.unsplash.com/photo-1528127269322-539801943592?w=1200&h=800&fit=crop',
        title: 'Venice Canal',
        description: 'Picturesque canal in Venice with colorful buildings and gondolas',
        date: '2023-03-18',
        orientation: 'landscape',
        tags: ['travel', 'urban'],
    },
    {
        id: 110,
        album: 'abstract',
        url: 'https://images.unsplash.com/photo-1557672172-298e090bd0f1?w=1200&h=1600&fit=crop',
        title: 'Color Explosion',
        description: 'Abstract explosion of colorful paint creating a dynamic pattern',
        date: '2023-02-27',
        orientation: 'portrait',
        tags: ['personal'],
    },
    {
        id: 111,
        album: 'beach',
        url: 'https://images.unsplash.com/photo-1471922694854-ff1b63b20054?w=1200&h=800&fit=crop',
        title: 'Tropical Paradise',
        description: 'Pristine white sand beach with crystal clear turquoise water',
        date: '2023-01-14',
        orientation: 'landscape',
        tags: ['travel'],
    },
    {
        id: 112,
        album: 'automotive',
        url: 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=1200&h=800&fit=crop',
        title: 'Classic Muscle Car',
        description: 'Vintage American muscle car with gleaming chrome and impeccable finish',
        date: '2022-12-08',
        orientation: 'landscape',
        tags: ['urban'],
    },
    {
        id: 113,
        album: 'flowers',
        url: 'https://images.unsplash.com/photo-1518621736915-f3b1c41bfd00?w=1200&h=1600&fit=crop',
        title: 'Spring Bouquet',
        description: 'Colorful spring flowers arrangement in vintage vase',
        date: '2022-11-05',
        orientation: 'portrait',
        tags: ['personal'],
    },
    {
        id: 114,
        album: 'wildlife',
        url: 'https://images.unsplash.com/photo-1503256207526-0d5d80fa2f47?w=1200&h=800&fit=crop',
        title: 'Wild Fox',
        description: 'Close-up of a wild fox in natural habitat looking straight at camera',
        date: '2022-10-12',
        orientation: 'landscape',
        tags: ['landscape'],
    },
    {
        id: 115,
        album: 'sunset',
        url: 'https://images.unsplash.com/photo-1495616811223-4d98c6e9c869?w=1200&h=800&fit=crop',
        title: 'Ocean Sunset',
        description: 'Dramatic sunset over the ocean with silhouette of rocky shoreline',
        date: '2022-09-19',
        orientation: 'landscape',
        tags: ['travel'],
    },
    {
        id: 116,
        album: 'winter',
        url: 'https://images.unsplash.com/photo-1517299321609-52687d1bc55a?w=1200&h=800&fit=crop',
        title: 'Snowy Cabin',
        description: 'Cozy wooden cabin in dense snow-covered pine forest',
        date: '2022-08-07',
        orientation: 'landscape',
        tags: ['landscape'],
    },
    {
        id: 117,
        album: 'autumn',
        url: 'https://images.unsplash.com/photo-1477414348463-c0eb7f1359b6?w=1200&h=1600&fit=crop',
        title: 'Fall Colors',
        description: 'Vibrant autumn leaves in shades of red, orange and yellow',
        date: '2022-07-24',
        orientation: 'portrait',
        tags: ['landscape'],
    },
    {
        id: 118,
        album: 'architecture',
        url: 'https://images.unsplash.com/photo-1494526585095-c41746248156?w=1200&h=800&fit=crop',
        title: 'Ancient Temple',
        description: 'Ancient stone temple with intricate carvings and historical significance',
        date: '2022-06-17',
        orientation: 'landscape',
        tags: ['architecture', 'travel'],
    },
    {
        id: 119,
        album: 'food',
        url: 'https://images.unsplash.com/photo-1482049016688-2d3e1b311543?w=1200&h=800&fit=crop',
        title: 'Breakfast Spread',
        description: 'Beautiful morning breakfast spread with pastries, fruits and coffee',
        date: '2022-05-12',
        orientation: 'landscape',
        tags: ['food'],
    },
    {
        id: 120,
        album: 'street',
        url: 'https://images.unsplash.com/photo-1542219550-37153d387c27?w=1200&h=800&fit=crop',
        title: 'Rainy Streets',
        description: 'Moody street scene with rain-soaked pavement and reflections of city lights',
        date: '2022-04-08',
        orientation: 'landscape',
        tags: ['urban'],
    },
    {
        id: 121,
        album: 'portraits',
        url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=1200&h=1600&fit=crop',
        title: 'Creative Portrait',
        description: 'Artistic portrait with unique lighting and composition',
        date: '2022-03-25',
        orientation: 'portrait',
        tags: ['personal'],
    },
    {
        id: 122,
        album: 'travel',
        url: 'https://images.unsplash.com/photo-1523592121529-f6dde35f079e?w=1200&h=800&fit=crop',
        title: 'Tokyo Street',
        description: 'Vibrant street in Tokyo at night with neon lights and bustling atmosphere',
        date: '2022-02-14',
        orientation: 'landscape',
        tags: ['travel', 'urban'],
    },
    {
        id: 123,
        album: 'nature',
        url: 'https://images.unsplash.com/photo-1465146344425-f00d5f5c8f07?w=1200&h=800&fit=crop',
        title: 'Wilderness Trail',
        description: 'Peaceful hiking trail through lush green forest',
        date: '2022-01-18',
        orientation: 'landscape',
        tags: ['landscape', 'travel'],
    },
    {
        id: 124,
        album: 'architecture',
        url: 'https://images.unsplash.com/photo-1487958449943-2429e8be8625?w=1200&h=1600&fit=crop',
        title: 'Urban Geometry',
        description:
            'Abstract architectural photograph highlighting geometric patterns of modern building',
        date: '2021-12-23',
        orientation: 'portrait',
        tags: ['architecture', 'urban'],
    },
    {
        id: 125,
        album: 'food',
        url: 'https://images.unsplash.com/photo-1485963631004-f2f00b1d6606?w=1200&h=800&fit=crop',
        title: 'Coffee Art',
        description: 'Beautifully crafted latte art in a coffee shop setting',
        date: '2021-11-15',
        orientation: 'landscape',
        tags: ['food'],
    },
    {
        id: 126,
        album: 'wildlife',
        url: 'https://images.unsplash.com/photo-1437622368342-7a3d73a34c8f?w=1200&h=800&fit=crop',
        title: 'Mountain Goat',
        description:
            'Wild mountain goat standing on a rocky ledge with mountains in the background',
        date: '2021-10-28',
        orientation: 'landscape',
        tags: ['landscape'],
    },
    {
        id: 127,
        album: 'portraits',
        url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=1200&h=1600&fit=crop',
        title: 'Character Portrait',
        description: "Close-up portrait capturing the character and intensity in a man's face",
        date: '2021-09-18',
        orientation: 'portrait',
        tags: ['personal'],
    },
];

// You can import the full set of photos from another file if needed
// import { fullPhotoSet } from './fullPhotoSet';
